riders:
  # Liste der Reiter, die gesucht werden sollen.
  - Max Mustermann

horses:
  # Liste der Pferde, die gesucht werden sollen
  - Epona

nations:
  # Equi-score-Ländercodes (wie im Event-Payload), z.B. GER
  - GER
